name: "parse and deploy"
on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '05 4 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: parse options and create search
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: nixbuild/nix-quick-install-action@master
      - name: Configure Nix cache
        uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}

      - name: extract-options-master (unstable)
        run: ./scripts/build_and_parse_hm_options.rb

      - name: update gitignore
        run: echo result > .gitignore

      - name: extract-options-release-25.05 (stable)
        env:
          HM_RELEASE: release-25.05
        run: ./scripts/build_and_parse_hm_options.rb
        
      - name: extract-options-release-24.11 (old-stable)
        env:
          HM_RELEASE: release-24.11
        run: ./scripts/build_and_parse_hm_options.rb

      - name: Build Hugo
        run: nix run nixpkgs#hugo -- --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages-${{ github.ref_name }}
          publish_dir: ./public
